/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import static com.mycompany.proyecto.Proyecto.proyectos;
import static com.mycompany.proyecto.Proyecto.tareas;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class AsignarTareasGerente extends javax.swing.JFrame {

    /**
     * Creates new form AsignarTareasGerente
     */
    public AsignarTareasGerente() {
        initComponents();
        llenarComboBoxMi();
        llenarComboBoxTarea();
    }
    
    public void llenarComboBoxMi(){
        
        Equipo equipoSeleccionado = null;
        for(Equipo e : Proyecto.equipos){
            if(e.getGerente().equals(PaginaGerente.usuario.getNombre())){
                equipoSeleccionado = e;
                for(Usuario u: equipoSeleccionado.getMiembros()){
                    miembroComboBox.addItem(u.getUsuario());
                }
                break;
            }
        }
          
    }
    
    public void llenarComboBoxTarea(){
     
        Proyectos proyectoSeleccionado = null;
        for(Proyectos p : Proyecto.proyectos){
            if(p.getNombreEquipo().equals(PaginaGerente.usuario.getNombreEquipo())){
                proyectoSeleccionado = p;
                for(Tarea t: proyectoSeleccionado.getTareas()){
                    tareaComboBox.addItem(t.getTituloTarea());
                }
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        miembroComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tareaComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Asignación de Tareas a Usuarios");

        jLabel2.setText("Miembro:");

        jLabel3.setText("Tarea:");

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu2.setText("Regresar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tareaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(miembroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tareaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(miembroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        boolean ingresado = false;
            
            for(Tarea t : Proyecto.tareas){
                String usuarioSeleccionado = miembroComboBox.getSelectedItem().toString();
                String usuarioTarea = t.getUsuario();
    
                if (usuarioSeleccionado != null && usuarioTarea != null && usuarioTarea.equals(usuarioSeleccionado)) {
                ingresado = true;
                break;
    }
            }
            if(ingresado){
                JOptionPane.showMessageDialog(this, "Tarea ya se encuentra asignada a otro usuario, por favor seleccione otro");
            }
            else{
                 
                Tarea tareaSeleccionada = null;
                for(Tarea t: Proyecto.tareas){
                    if(t.getTituloTarea().equals(tareaComboBox.getSelectedItem().toString())){
                        tareaSeleccionada = t;
                        break;
                    }
                }
                String usuario = miembroComboBox.getSelectedItem().toString();
                
                if(usuario!=null && tareaSeleccionada!=null){
                    tareaSeleccionada.setUsuario(usuario);
                    JOptionPane.showMessageDialog(this, "Tarea asignada exitosamente");
                    tareaComboBox.removeItem(tareaSeleccionada);
                }
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> miembroComboBox;
    private javax.swing.JComboBox<String> tareaComboBox;
    // End of variables declaration//GEN-END:variables
}
