/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import static com.mycompany.proyecto.Proyecto.usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class CreacionEquipos extends javax.swing.JFrame {
    int id = Proyecto.equipos.size() + 1;
    private Equipo agregar;
    

    /**
     * Creates new form CreacionEquipos
     */
    public CreacionEquipos() {
        initComponents();
        llenarComboBoxGe();
        llenaridEquipo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gerenteComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nombreEquipoTextField = new javax.swing.JTextField();
        idEquipoTextField = new javax.swing.JTextField();
        crearButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Creación de Equipos");

        jLabel2.setText("Nombre del Equipo:");

        jLabel3.setText("ID del Equipo:");

        jLabel4.setText("Gerente de Equipo:");

        nombreEquipoTextField.setToolTipText("");

        idEquipoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEquipoTextFieldActionPerformed(evt);
            }
        });

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        jMenu2.setText("Regresar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(idEquipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreEquipoTextField)
                                    .addComponent(gerenteComboBox, 0, 109, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(crearButton)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreEquipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idEquipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerenteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(crearButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    public void llenarComboBoxGe(){
        
        for(Usuario i: usuarios){
            if("Gerente".equals(i.getRol())){
                gerenteComboBox.addItem(i.getNombre());
            }
        }
    }
    
    
    public void llenaridEquipo(){
        
        idEquipoTextField.setText(String.valueOf(id));
    }
    
    private void idEquipoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEquipoTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idEquipoTextFieldActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        // TODO add your handling code here:

        boolean ingresado = false;

        for (Equipo e: Proyecto.equipos){
            if (e.getNombreEquipo().equals(nombreEquipoTextField.getText())){
                ingresado = true;
                break;
            }
        }
        if(ingresado){
            JOptionPane.showMessageDialog(this, "Nombre de Equipo en uso, por favor elija otro");
        }

        else{
            boolean ingresado3 = false;
            for(Equipo e: Proyecto.equipos){
                if (e.getGerente().equals(gerenteComboBox.getSelectedItem())){
                    ingresado3 = true;
                    break;
                }
            }
            if(ingresado3){
                JOptionPane.showMessageDialog(this, "Gerente ya se encuentra asignado a otro equipo, por favor seleccione otro");
            }
            else{

                String nombreEquipo = nombreEquipoTextField.getText();
                String gerente = gerenteComboBox.getSelectedItem().toString();

                Equipo equipoNuevo = new Equipo();
                equipoNuevo.setNombreEquipo(nombreEquipo);
                equipoNuevo.setId(id);
                equipoNuevo.setGerente(gerente);

                Proyecto.equipos.add(equipoNuevo);
                
                    Equipo equipoSeleccionado = equipoNuevo;

                    Usuario miembroSeleccionado = null;
                    for(Usuario u: Proyecto.usuarios){
                        if(u.getNombre().equals(gerenteComboBox.getSelectedItem().toString())){
                            miembroSeleccionado = u;
                            break;
                        }
                    }

                    if(equipoSeleccionado!=null && miembroSeleccionado!=null){
                        equipoSeleccionado.asignarMiembro(miembroSeleccionado);
                        nombreEquipoTextField.setText("");
                        idEquipoTextField.setText("");
                        gerenteComboBox.removeItem(gerente);
                        JOptionPane.showMessageDialog(this, "Equipo creado con exitosamente");
                    }
            }
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearButton;
    private javax.swing.JComboBox<String> gerenteComboBox;
    private javax.swing.JTextField idEquipoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nombreEquipoTextField;
    // End of variables declaration//GEN-END:variables
}
